namespace ServiceExcellence.Api.Services;

public class StorageOptions
{
    public const string Section = "Storage";

    public string UploadPath { get; set; } = "uploads";
    public long MaxFileSizeBytes { get; set; } = 10 * 1024 * 1024;
}

public interface IFileStorage
{
    /// <summary>Content type for an allowed extension, or null when the extension is not allowed.</summary>
    string? GetContentType(string fileName);
    long MaxFileSizeBytes { get; }
    Task<string> SaveAsync(Stream content, string fileName, CancellationToken cancellationToken = default);
    Stream? OpenRead(string storedName);
    void Delete(string storedName);
}

/// <summary>Stores attachment files on local disk (a Docker volume in containers) under random names.</summary>
public class LocalFileStorage : IFileStorage
{
    private static readonly Dictionary<string, string> AllowedTypes = new(StringComparer.OrdinalIgnoreCase)
    {
        [".jpg"] = "image/jpeg",
        [".jpeg"] = "image/jpeg",
        [".png"] = "image/png",
        [".gif"] = "image/gif",
        [".webp"] = "image/webp",
        [".pdf"] = "application/pdf"
    };

    private readonly string _root;

    public LocalFileStorage(Microsoft.Extensions.Options.IOptions<StorageOptions> options, IWebHostEnvironment env)
    {
        var path = options.Value.UploadPath;
        _root = Path.IsPathRooted(path) ? path : Path.Combine(env.ContentRootPath, path);
        MaxFileSizeBytes = options.Value.MaxFileSizeBytes;
        Directory.CreateDirectory(_root);
    }

    public long MaxFileSizeBytes { get; }

    public string? GetContentType(string fileName) =>
        AllowedTypes.TryGetValue(Path.GetExtension(fileName), out var type) ? type : null;

    public async Task<string> SaveAsync(Stream content, string fileName, CancellationToken cancellationToken = default)
    {
        var storedName = $"{Guid.NewGuid():N}{Path.GetExtension(fileName).ToLowerInvariant()}";
        await using var file = File.Create(FullPath(storedName));
        await content.CopyToAsync(file, cancellationToken);
        return storedName;
    }

    public Stream? OpenRead(string storedName)
    {
        var path = FullPath(storedName);
        return File.Exists(path) ? File.OpenRead(path) : null;
    }

    public void Delete(string storedName)
    {
        var path = FullPath(storedName);
        if (File.Exists(path)) File.Delete(path);
    }

    private string FullPath(string storedName) =>
        // Stored names are generated by SaveAsync; strip any directory part defensively.
        Path.Combine(_root, Path.GetFileName(storedName));
}
